### ISSUE TITLE
add table metadata to the responses?

### ISSUE THREAD

**Issue by denislepage** [BirdStudiesCanada/NatureCountsAPI#5]
To be discussed. I mentioned to Steffi the option of relying on the API to provide details sufficient to build the metadata tables on the R side.

There could be an optional toggle for any given call which instead of returning data return something like this:

```
{"db_metadata":
	{
		"table_name":"species",
		"fields": [
			{"name": "species_id", "type": "int", "length": 4 },
			{"name": "english_name", "type": "varchar", "length": 100 },
			{"name": "french_name", "type": "varchar", "length": 100  },
			{"name": "group_name", "type": "varchar", "length": 60  },
			{"name": "sort_order", "type": "int", "length": 4  }
		],
		"keys": ["species_id"]
	}
}
```
We possibly also would need an API call that returns the list of entry points, to support adding new tables. 

Perhaps it's not worth it, but I find the idea appealing. It minimizes the amount of upkeep we have to do on the R package, for one thing, and ensures that there are no discrepancies. I'm open to discussion if Steffi in particular doesn't see the appeal.

We can actually read the field info from the data itself. The only thing we'd have to specify are the proc names, the remote table names and the primary keys for each table.

```
Map<String, Object> meta = new LinkedHashMap<>();
String sql = "EXEC prAPI_collections ?";
try (SQLPreparedStmt stmt = projInfo.getDb().getSQLPreparedStmt(null, sql, null);) {
	meta.put("table_name", "collections");
	meta.put("keys", Arrays.asList(new String[] {"collection"}));
	stmt.setParameter(1,  "EN");
	SQLResult r = stmt.executeQuery();
	ResultSetMetaData rmd = r.getMetaData();
	List<Map<String, Object>> fields = new ArrayList<>(rmd.getColumnCount());
	for (int i = 1; i <= rmd.getColumnCount(); i++) {
		Map<String, Object> field = new LinkedHashMap<>(4);
		field.put("name", rmd.getColumnName(i));
		field.put("type", rmd.getColumnTypeName(i));
		field.put("length", rmd.getColumnDisplaySize(i));
		field.put("precision", rmd.getPrecision(i));
		field.put("scale", rmd.getScale(i));
		fields.add(field);
	}
	meta.put("fields",  fields);
	r.close();
}
System.out.println(JSONValue.toJSONString(meta));
```

**Comment by steffilazerte** [comment]
Reiterating what I said in the email (for Paul's benefit), and I think, changing some things, to reflect a different (better?) understanding of what you're suggesting: 

I think that there is great appeal in making it so that the R package is robust to changes on the server!

However, R is pretty robust: we don't have to tell it what data to expect. When it downloads metadata, it just does it, we don't have to specify what structure to expect. So for metadata this really isn't necessary.

However, for the actual _data_ download, there is something to this idea. I had assumed that the update metadata function would also be used to update the blank data template I use to create the SQL database, but have I misunderstood? Is it likely that the data fields will change independently of changes made to the metadata?

If that is the case, we could (for the data table, not the metadata):
a) use another Version number for the actual data (which could be checked for resuming data, as well)
b) have R download a new sample of data for the the table template each time it will create a new SQL database (as opposed to only when manually requested)
c) use the first set of data returned by the API to specify the table structure
d) have R download the field specifications (what you are suggesting here)

My feeling is that b) or c) are the simplest, as they doesn't require any additions to the API and are simple to implement.

Have I better understood the idea this time around?
